In [2]:
from utils.constantes import DATA_CLEAN_PATH
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [9]:
def nombre_aglomerado(codigo):
    """
    Devuelve el nombre del aglomerado a partir de su código.

    Args:
        codigo (str): Código del aglomerado.

    Returns:
        str or None: Nombre del aglomerado o None si no existe.
    """
    dic_aglomerados = {
        '2': 'Gran La Plata',
        '3': 'Bahía Blanca - Cerri',
        '4': 'Gran Rosario',
        '5': 'Gran Santa Fé',
        '6': 'Gran Paraná',
        '7': 'Posadas',
        '8': 'Gran Resistencia',
        '9': 'Comodoro Rivadavia - Rada Tilly',
        '10': 'Gran Mendoza',
        '12': 'Corrientes',
        '13': 'Gran Córdoba',
        '14': 'Concordia',
        '15': 'Formosa',
        '17': 'Neuquén - Plottier',
        '18': 'Santiago del Estero - La Banda',
        '19': 'Jujuy - Palpalá',
        '20': 'Río Gallegos',
        '22': 'Gran Catamarca',
        '23': 'Gran Salta',
        '25': 'La Rioja',
        '26': 'Gran San Luis',
        '27': 'Gran San Juan',
        '29': 'Gran Tucumán - Tafí Viejo',
        '30': 'Santa Rosa - Toay',
        '31': 'Ushuaia - Río Grande',
        '32': 'Ciudad Autónoma de Buenos Aires',
        '33': 'Partidos del GBA',
        '34': 'Mar del Plata',
        '36': 'Río Cuarto',
        '38': 'San Nicolás - Villa Constitución',
        '91': 'Rawson - Trelew',
        '93': 'Viedma - Carmen de Patagones'
    }
    return dic_aglomerados.get(codigo)

In [ ]:
archivo_clean_path = DATA_CLEAN_PATH / "usu_clean_individual.csv"
df = pd.read_csv(archivo_clean_path, delimiter=",",low_memory=False)

df

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH,CH04_str,NIVEL_ED_str,CONDICION_LABORAL,UNIVERSITARIO
0,TQRMNOPUTHLMKQCDEGGFB00852588,2024,1,1,3,1,42,S,10,439,...,12.0,12,12.0,NaN,12,0,femenino,secundario incompleto,ocupado dependiente,0
1,TQRMNOPUTHLMKQCDEGGFB00852588,2024,1,1,4,1,42,S,10,439,...,12.0,12,12.0,NaN,12,0,femenino,superior o universitario,inactivo,1
2,TQRMNOPUTHLMKQCDEGGFB00852588,2024,1,1,5,0,42,S,10,439,...,12.0,12,12.0,NaN,12,0,femenino,sin informacion,fuera de categoria,0
3,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,1,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,masculino,secundario completo,ocupado dependiente,0
4,TQRMNOPPWHLLKRCDEGGFB00852574,2024,1,1,2,1,42,S,10,675,...,6.0,6,6.0,NaN,6,1610,femenino,secundario completo,ocupado dependiente,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141531,TQRMNOTTSHLNKNCDEHMHF00806207,2023,3,1,2,1,42,N,26,213,...,8.0,9,NaN,8.0,9,218,masculino,primario incompleto,inactivo,2
141532,TQRMNOUTXHJOKOCDEHMHF00784706,2023,3,1,1,1,42,N,26,164,...,2.0,2,NaN,2.0,2,176,masculino,primario incompleto,inactivo,0
141533,TQRMNOUTXHJOKOCDEHMHF00784706,2023,3,1,2,1,42,N,26,164,...,2.0,2,NaN,2.0,2,176,femenino,primario incompleto,inactivo,0
141534,TQRMNOUTXHJOKOCDEHMHF00784706,2023,3,1,3,1,42,N,26,164,...,2.0,2,NaN,2.0,2,176,masculino,primario incompleto,inactivo,0
141535,TQRMNOPXWHLNKQCDEHMHF00806210,2023,3,1,1,1,42,N,26,124,...,12.0,12,NaN,12.0,12,0,femenino,superior o universitario,ocupado dependiente,1

In [ ]:
df['PP09A_ESP'] = df['PP09A_ESP'].fillna(0)
df['PP09A_ESP']

0         0
1         0
2         0
3         0
4         0
         ..
141531    0
141532    0
141533    0
141534    0
141535    0
Name: PP09A_ESP, Length: 141536, dtype: object

In [ ]:
df_anios =  sorted(df["ANO4"].astype(str).unique())
df_trimestres = sorted(df['TRIMESTRE'].astype(str).unique())
# anio_seleccionado = todos

In [ ]:
# df con columnas de edad y sexo 
df_filtrado = df[["PONDERA","CH04", "CH06"]].copy()


rango_anios = range(0,101,10)
etiquetas =  [f"{i}-{i+9}" for i in rango_anios[:-1]] 

df_filtrado["CH06"] = pd.to_numeric(df_filtrado["CH06"], errors="coerce")
df_filtrado["grupos_edad"] = pd.cut(df_filtrado["CH06"],bins=rango_anios , labels=etiquetas)

df_filtrado["CH04"] = df_filtrado["CH04"].apply(lambda x: "M" if x == 1 else "F")
df_filtrado = df_filtrado.groupby(["CH04","grupos_edad"])["PONDERA"].sum().reset_index()

df_filtrado

C:\Users\Usuario\AppData\Local\Temp\ipykernel_18088\1876331794.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_filtrado = df_filtrado.groupby(["CH04","grupos_edad"])["PONDERA"].sum().reset_index()

   CH04 grupos_edad  PONDERA
0     F         0-9  2104948
1     F       10-19  2378439
2     F       20-29  2170358
3     F       30-39  2116476
4     F       40-49  2018796
5     F       50-59  1557663
6     F       60-69  1351334
7     F       70-79   959103
8     F       80-89   368272
9     F       90-99    65092
10    M         0-9  2218035
11    M       10-19  2578370
12    M       20-29  2097435
13    M       30-39  1985981
14    M       40-49  1973348
15    M       50-59  1522848
16    M       60-69  1087231
17    M       70-79   659582
18    M       80-89   201966
19    M       90-99    17062

In [35]:
df_hombres = df_filtrado[df_filtrado["CH04"] == 'M'].copy()
df_mujeres = df_filtrado[df_filtrado["CH04"] == 'F'].copy()
df_pivot = df_filtrado.pivot(index="grupos_edad",columns="CH04",values="PONDERA")
df_pivot

CH04               F        M
grupos_edad
0-9          2104948  2218035
10-19        2378439  2578370
20-29        2170358  2097435
30-39        2116476  1985981
40-49        2018796  1973348
50-59        1557663  1522848
60-69        1351334  1087231
70-79         959103   659582
80-89         368272   201966
90-99          65092    17062

In [ ]:
x = np.arange(len(df_hombres.index))
ancho = 0.35 
valores_y = [0,1000000,2000000,3000000,4000000,5000000]
labels_y = ["0","1.000.000","2.000.000","3.000.000","4.000.000","5.000.000"]

fig, ax = plt.subplots()

ax.bar(x - ancho / 2 , df_hombres["PONDERA"], width=ancho , label="hombres")
ax.bar(x + ancho / 2 , df_mujeres["PONDERA"], width=ancho , label="mujeres")

ax.set_xlabel("grupos por edad") 
ax.set_ylabel("cantidad de gente") 


ax.set_xticklabels(df_hombres["grupos_edad"])
ax.set_yticklabels(labels_y)
ax.legend()

In [ ]:
ultimo_anio = int(df["ANO4"].unique().max())
df_ult_anio = df[df["ANO4"] == ultimo_anio]
ultimo_trim = int(df_ult_anio["TRIMESTRE"].unique().max())
df_reciente = df_ult_anio[df_ult_anio["TRIMESTRE"] == ultimo_trim]

In [ ]:
df_aglomerado = df[["AGLOMERADO","PONDERA","CH06"]].copy()

df_aglomerado['nombre_aglomerado'] = df_aglomerado['AGLOMERADO'].astype(str).apply(nombre_aglomerado)
df_aglomerado = df_aglomerado.groupby(["AGLOMERADO","nombre_aglomerado",]).mean("CH06")
df_aglomerado['CH06'] = df_aglomerado['CH06'].round(2)
df_aglomerado

                                                 PONDERA   CH06
AGLOMERADO nombre_aglomerado
2          Gran La Plata                      801.439655  35.82
3          Bahía Blanca - Cerri               311.273875  37.42
4          Gran Rosario                       784.858915  36.74
5          Gran Santa Fé                      396.312395  36.50
6          Gran Paraná                        201.891243  37.78
7          Posadas                            317.099564  35.27
8          Gran Resistencia                   325.913055  34.62
9          Comodoro Rivadavia - Rada Tilly    269.621574  34.60
10         Gran Mendoza                       562.231317  36.92
12         Corrientes                         366.838346  35.26
13         Gran Córdoba                       770.341856  35.25
14         Concordia                          120.632504  34.26
15         Formosa                            201.885949  36.12
17         Neuquén - Plottier                 267.406606  36.95
18         Santiago del Estero - La Banda     279.768210  33.26
19         Jujuy - Palpalá                    232.869584  35.85
20         Río Gallegos                       200.885920  36.83
22         Gran Catamarca                     154.752173  34.18
23         Gran Salta                         342.493625  35.43
25         La Rioja                           163.039796  34.16
26         Gran San Luis                      194.039343  36.33
27         Gran San Juan                      347.804238  34.96
29         Gran Tucumán - Tafí Viejo          432.838659  34.55
30         Santa Rosa - Toay                  146.330869  37.20
31         Ushuaia - Río Grande               192.422673  35.08
32         Ciudad Autónoma de Buenos Aires   2066.420811  41.89
33         Partidos del GBA                  2250.264873  36.72
34         Mar del Plata                      673.937585  37.75
36         Río Cuarto                         163.406932  36.72
38         San Nicolás - Villa Constitución   136.269213  36.45
91         Rawson - Trelew                    148.284124  36.76
93         Viedma - Carmen de Patagones        85.654321  36.89

Dependencia demográfica = ((Población de 0 a 14 años + Población de 65 años o más) / Población de 15 a 64 años ) * 100

In [16]:
aglo_seleccionado = 32

In [ ]:
df_activos = df[(df["AGLOMERADO"] == aglo_seleccionado) & (df["CH06"].between(15,64,inclusive="both")) ][["ANO4","TRIMESTRE","PONDERA"]].copy()
df_inactivos = df[(df["AGLOMERADO"] == aglo_seleccionado) & ( ~df["CH06"].between(15,64,inclusive="both")) ][["ANO4","TRIMESTRE","PONDERA"]].copy()

df_activos = df_activos.groupby(["ANO4","TRIMESTRE"]).sum("PONDERA").reset_index()
df_inactivos = df_inactivos.groupby(["ANO4","TRIMESTRE"]).sum("PONDERA").reset_index()

df_activos["grupo"] = "activos"
df_inactivos["grupo"] = "inactivos"

df_union = pd.concat([df_inactivos, df_activos])

df_union['periodo'] = df_union['ANO4'].astype(str) + 'T' + df_union['TRIMESTRE'].astype(str)
df_union = df_union[["PONDERA","grupo","periodo"]]

df_union = df_union.pivot(index="grupo",columns="periodo",values="PONDERA")

df_union["cociente"] = (df_union["inactivos"] / df_union["activos"] * 100).round(2)
df_union

KeyError: 'inactivos'

In [148]:
df_edad = df[["ANO4","PONDERA","TRIMESTRE","CH06"]].copy()

df_edad['periodo'] = df_edad['ANO4'].astype(str) + 'T' + df_edad['TRIMESTRE'].astype(str)

df_edad = df_edad.groupby(["ANO4","CH06","TRIMESTRE","periodo"]).sum("PONDERA")
df_edad= df_edad.reset_index()

df_edad = df_edad.pivot(index="CH06", columns="periodo",values="PONDERA")

df_edad.index.name = 'edad'

# Calculamos la media ponderada de la edad por periodo
media_edad_ponderada = ((df_edad.mul(df_edad.index, axis=0)).sum() / df_edad.sum() ).round(2)

# Convertimos a DataFrame si lo querés como tal
media_edad_ponderada_df = media_edad_ponderada.to_frame(name='media_edad')
media_edad_ponderada_df

         media_edad
periodo
2023T3        34.96
2024T1        35.15
2024T2        35.23